# Generated by Django 3.2.6 on 2021-08-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='item',
        ),
    ]
