# Generated by Django 4.1.4 on 2022-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
