# Generated by Django 3.2.6 on 2021-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_technology_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='item',
            field=models.ManyToManyField(to='web.TechnologyItem'),
        ),
    ]
