# Generated by Django 3.2.6 on 2021-08-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_technology_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyitem',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
