# Generated by Django 3.2.6 on 2021-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_technologyitem_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyitem',
            name='link',
        ),
        migrations.AddField(
            model_name='technology',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
