# Generated by Django 4.1.4 on 2022-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
