# Generated by Django 3.2.6 on 2021-08-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210808_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyitem',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.link'),
        ),
    ]
