# Generated by Django 4.1.4 on 2022-12-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='hashtags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
