# Generated by Django 4.1.4 on 2022-12-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_tutorial_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='like_score',
            field=models.IntegerField(default=0),
        ),
    ]
