# Generated by Django 3.2.6 on 2021-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
