# Generated by Django 4.1.4 on 2022-12-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tutorial'),
        ),
    ]
