# Generated by Django 4.1.4 on 2022-12-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_feedback_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons'),
        ),
    ]
