# Generated by Django 3.2.6 on 2021-08-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
