# Generated by Django 3.2.6 on 2021-08-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_item_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
