# Generated by Django 3.2.14 on 2022-12-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='tutorials/images/')),
                ('tags', models.ManyToManyField(to='web.Tag')),
            ],
        ),
    ]
