# Generated by Django 4.1.4 on 2022-12-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_feedback_created_at_feedback_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertutorials',
            name='content',
        ),
        migrations.AddField(
            model_name='usertutorials',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.tutorial'),
        ),
    ]
